org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-enderio
addon_name=BlueMap Ender IO Add-on
addon_version=0.1.0-alpha.3
addon_group=io.github.jan-guenter
artifact_id=bluemap-enderio-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=67131
accepted_jar_sha256=2f7b61a7bdd53bc5cce8181e2575e31b681d26ea734c9e6563c1af7c0fee7d1c
accepted_sources_jar_size=51775
accepted_sources_jar_sha256=e83cf1420e27fbc5e9cd1df2ed0c5f27bc6ca8974867eb3b33cc501ad8da1646
accepted_pom_size=1343
accepted_pom_sha256=6cdc740cbaf72cade03c7107bb002878eb9a2035dcf36770fe38876c269a91df
accepted_module_size=2817
accepted_module_sha256=e3e231410f6cc441f28175e84ac1e7b56448d3551ad122d1be8b3a0e1821ed59
