org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-enderio
addon_name=BlueMap Ender IO Add-on
addon_version=0.1.0-alpha.2
addon_group=io.github.jan-guenter
artifact_id=bluemap-enderio-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=58994
accepted_jar_sha256=9b999235340f6ebc9973053b16ccd5c53aa04966076558457d82e1bbaf708cd6
accepted_sources_jar_size=45928
accepted_sources_jar_sha256=29d5280d30119b986dd85291b316d754c889f1d444e282ff95699e7d2535c5a8
accepted_pom_size=1343
accepted_pom_sha256=d6035bd606438f03d8d84999b911a70c9b803fe0e88417b95aa3210592502311
accepted_module_size=2817
accepted_module_sha256=15efc5326b4ab37b8669b58fe2dfc11c7518a8f11a84683fda82a44e0211fd48
