org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-enderio
addon_name=BlueMap Ender IO Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-enderio-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=53872
accepted_jar_sha256=4434f9f7da28b157ca83e17ef5a6eaf56fee830c0044cd987e4a78b4f9f2b41a
accepted_sources_jar_size=40617
accepted_sources_jar_sha256=700a28567094bf3d44e53c524dc0481cd3ceb10a162369b26290641af7bb423c
accepted_pom_size=1343
accepted_pom_sha256=a0d326fb533f65acff2ad4f860b81a4200bb179a3d5e58d90ccfc502af8d1a97
accepted_module_size=2817
accepted_module_sha256=f387963a0237a19bec3c02d18697e4ecc1243304c1e885eaae28cc6e69d73429
